[package]
name = "noop-nrelay-wasmedge"
version = "0.0.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
tokio-tungstenite_wasi = "0.18.0"
tokio_wasi = { version = "1.25.2", features = ["rt", "macros", "net", "time", "io-util"] }
serde_json = "1.0.108"
valq = "0.1.0"
